---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodockerfileapp

spec:
  selector:
    matchLabels:
      app: demodockerfileapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demodockerfileapp
    spec:
      containers:
      - name: demodockerfileapp
        image: briansandiford/demodockerfileapp
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
